name: flutter_dasher
description: A new Flutter onboarding project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_hooks: ^0.20.4
  flutter_inappwebview: ^6.0.0
  flutter_svg: ^2.0.9
  riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  dio: ^5.4.0
  flutter_secure_storage: ^9.0.0
  japx: ^2.0.4
  loggy: ^2.0.1+1
  hooks_riverpod: ^2.4.9
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.9
  flutter_gen_runner: ^5.4.0
  flutter_loggy: ^2.0.1
  freezed_annotation: ^2.0.3
  cached_network_image: ^3.3.1
  twitter_oauth2_pkce: ^1.0.2
  twitter_api_v2: ^4.9.4
  intl: ^0.19.0
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_gen: ^5.4.0
  build_runner: ^2.4.8
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  custom_lint: ^0.5.8
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7

flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/png/
    - assets/svg/

flutter_icons:
  image_path: 'assets/app_icons/app_icon.png'
  android: true
  ios: true
  remove_alpha_ios: true

flutter_native_splash:
  color: "#1DA1F2"
  image: assets/images/splash_center_logo.png